### PR TITLE
Fix watch service on macOS 11

### PR DESCRIPTION
**Pull request by kitharoidos**
See [this issue](https://github.com/boot-clj/boot/issues/765).

### CODE REVIEW

**Comment by truppert-mdsol** [comment]
@kitharoidos Thanks for finding the fix for this!  It sounds like they'd be happy to merge into the parent repo if a PR were raised.  Would you mind raising a PR there?

I don't want to steal your thunder by creating my own fork with exactly your changes just to get them added in upstream.

**Comment by kitharoidos** [comment]
> @kitharoidos Thanks for finding the fix for this! It sounds like they'd be happy to merge into the parent repo if a PR were raised. Would you mind raising a PR there?
> 
> I don't want to steal your thunder by creating my own fork with exactly your changes just to get them added in upstream.

I tried opening a PR against their master branch but apparently I don't have the permissions. I asked them for the permissions a long time ago, no response, will ping them again.

**Comment by truppert-mdsol** [comment]
Not possible using this page?  https://github.com/boot-clj/boot/compare/master...kitharoidos:master.  Once you fill out the title and description, I believe the button should become clickable.

**Comment by kitharoidos** [comment]
> Not possible using this page? [boot-clj/boot@master...kitharoidos:master](https://github.com/boot-clj/boot/compare/master...kitharoidos:master). Once you fill out the title and description, I believe the button should become clickable.

Ah, that worked, thanks! Previously, I only tried submitting the PR from IntelliJ IDEA (it usually works). Here is the PR:
https://github.com/boot-clj/boot/pull/766

**Pull request merged**
